### ISSUE TITLE
能否写一个使用说明？

### ISSUE THREAD

**Issue by lenngennd** [yumueat/TcCourse_downloader#1]
能否写一个使用说明？

**Comment by yumueat** [comment]
你可以查看README文件，里面有详细的说明

**Comment by lenngennd** [comment]
第一个截图的界面我都不知道怎么搞出来

**Comment by yumueat** [comment]
第一个截图的界面运行代码就出来了

**Comment by lenngennd** [comment]
都试了一遍，然后又安装了缺少的依赖，能正常使用了，命令是python downloader.py。
No module named 'Crypto'这是个坑，解决方法：
1.pip install pycryptodome
2.Python\Python38\Lib\site-packages，找到这个路径，下面有一个文件夹叫做crypto,将小写c改成大写C就ok了。
